# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# Add nbqa liniting to pre-commit
-   repo: local
    hooks:
    -   id: static-analysis
        name: Static analysis
        entry: "scripts/static-pre-commit.sh"
        language: python
        language_version: python3.12
        types: [python]
        require_serial: true
        verbose: true

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json