# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Downloading.ipynb.

# %% auto 0
__all__ = ['logger']

# %% ../nbs/Downloading.ipynb 2
from os import environ
import re
from pathlib import Path
import tempfile
from typing import Union, Optional, Tuple, Dict, Any
from contextlib import contextmanager
from urllib.parse import quote_plus as urlquote
from urllib.parse import unquote_plus as urlunquote
from datetime import datetime, timedelta

from sqlalchemy.engine import Connection, create_engine
import pandas as pd
import dask.dataframe as dd

# %% ../nbs/Downloading.ipynb 3
from .logger import get_logger

logger = get_logger(__name__)

# %% ../nbs/Downloading.ipynb 10
def get_clickhouse_params_from_env_vars() -> Dict[str, Union[str, int]]:
    return dict(
        username=environ["KAFKA_CH_USERNAME"],
        password=environ["KAFKA_CH_PASSWORD"],
        host=environ["KAFKA_CH_HOST"],
        database=environ["KAFKA_CH_DATABASE"],
        port=int(environ["KAFKA_CH_PORT"]),
        protocol=environ["KAFKA_CH_PROTOCOL"],
        table=environ["KAFKA_CH_TABLE"],
    )
