# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Helpers.ipynb.

# %% auto 0
__all__ = ['get_aio_kafka_config', 'TaskType', 'ModelTrainingRequest', 'StartPrediction']

# %% ../nbs/Helpers.ipynb 2
from enum import Enum
from os import environ
from typing import Optional, Dict, Any

from aiokafka.helpers import create_ssl_context
from pydantic import BaseModel, Field, NonNegativeInt

# %% ../nbs/Helpers.ipynb 3
def get_aio_kafka_config() -> Dict[str, Any]:
    kafka_server_url = environ["KAFKA_HOSTNAME"]
    kafka_server_port = environ["KAFKA_PORT"]

    kafka_bootstrap_servers = (
        f":{kafka_server_port},".join(kafka_server_url.split(","))
        + f":{kafka_server_port}"
    )
    return {
        "bootstrap_servers": kafka_bootstrap_servers,
        "security_protocol": "SASL_SSL",
        "sasl_mechanism": environ["KAFKA_SASL_MECHANISM"],
        "sasl_plain_username": environ["KAFKA_API_KEY"],
        "sasl_plain_password": environ["KAFKA_API_SECRET"],
        "ssl_context": create_ssl_context(),
    }

# %% ../nbs/Helpers.ipynb 4
class TaskType(str, Enum):
    churn = "churn"
    propensity_to_buy = "propensity_to_buy"


class ModelTrainingRequest(BaseModel):
    AccountId: NonNegativeInt = Field(
        ..., examples=[202020], description="ID of an account"
    )
    ApplicationId: Optional[str] = Field(
        default=None,
        examples=["TestApplicationId"],
        description="Id of the application in case there is more than one for the AccountId",
    )
    ModelId: str = Field(
        ...,
        examples=["ChurnModelForDrivers"],
        description="User supplied ID of the model trained",
    )
    task_type: TaskType = Field(
        ..., description="Model type, only 'churn' is supported right now"
    )
    total_no_of_records: NonNegativeInt = Field(
        ...,
        examples=[1_000_000],
        description="approximate total number of records (rows) to be ingested",
    )


class StartPrediction(BaseModel):
    AccountId: NonNegativeInt = Field(
        ..., examples=[202020], description="ID of an account"
    )
    ApplicationId: Optional[str] = Field(
        default=None,
        examples=["TestApplicationId"],
        description="Id of the application in case there is more than one for the AccountId",
    )
    ModelId: str = Field(
        ...,
        examples=["ChurnModelForDrivers"],
        description="User supplied ID of the model trained",
    )

    task_type: TaskType = Field(
        ...,
        examples=["churn"],
        description="Name of the model used (churn, propensity to buy)",
    )
