# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Training.ipynb.

# %% auto 0
__all__ = ['root_path', 'downloading_group_id', 'training_group_id']

# %% ../nbs/Training.ipynb 2
from os import environ
from pathlib import Path

# %% ../nbs/Training.ipynb 3
root_path = Path(environ["ROOT_PATH"])
downloading_group_id = environ["DOWNLOADING_GROUP_ID"]
training_group_id = environ["TRAINING_GROUP_ID"]
