name: Check message everyday for infobip_prediction topic

on:
  # everyday at 03:00
  schedule:
    - cron: "0 3 * * *"
  # or manually
  workflow_dispatch:

jobs:
  check-msg-everyday:
    name: Check message everyday for infobip_prediction topic
    strategy:
      fail-fast: false
      matrix:
        server: ["staging", "prod"]
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    container:
      image: ubuntu:22.04
    env:
      ACCESS_REP_TOKEN: ${{ secrets.ACCESS_REP_TOKEN }}
      PROD_CONFIG: ${{ secrets.PROD_CONFIG }}
      STAGING_CONFIG: ${{ secrets.STAGING_CONFIG }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - run: apt-get update -y && apt-get install openssh-client git -y

      - run: echo "SERVER=${{ matrix.server }}" >> $GITHUB_ENV
      - run: if [[ $KAFKA_DOMAIN == "staging" ]]; then printenv STAGING_CONFIG > "$(pwd)/.env" ; else printenv PROD_CONFIG > "$(pwd)/.env" ; fi;

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiokafka python-dotenv
      - run: python scripts/check_msg.py
